export const QUERY_ALL_USERS = "QUERY_ALL_USERS";

export const QUERY_USER = "QUERY_USER";
export const CREATE_ORDER = "CREATE_ORDER";
export const QUERY_CARS = "QUERY_CARS";
export const QUERY_CAR = "QUERY_CAR";
export const QUERY_CAR_BY_MAKE = "QUERY_CAR_BY_MAKE";
export const QUERY_CAR_BY_YEAR = "QUERY_CAR_BY_YEAR";

export const QUERY_CAR_BY_MILEAGE = "QUERY_CAR_BY_MILEAGE";
export const CHECKOUT = "CHECKOUT";
export const CREATE_USER = "CREATE_USER";
export const CREATE_CAR = "CREATE_CAR";
export const ADD_CAR_TO_WATCHLIST = "ADD_CAR_TO_WATCHLIST";
export const REMOVE_CAR_FROM_WATCHLIST = "REMOVE_CAR_FROM_WATCHLIST";
export const CAR_SOLD= "CAR_SOLD";
